// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9UQWdfrV9oWjMYsGjqD8ToxRK-Jx0IxQ',
    appId: '1:9527223797:web:7ff0fec7a325c921996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    authDomain: 'brothers-creative.firebaseapp.com',
    storageBucket: 'brothers-creative.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9UQWdfrV9oWjMYsGjqD8ToxRK-Jx0IxQ',
    appId: '1:9527223797:android:7ff0fec7a325c921996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9UQWdfrV9oWjMYsGjqD8ToxRK-Jx0IxQ',
    appId: '1:9527223797:ios:7ff0fec7a325c921996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
    iosBundleId: 'com.example.brotherAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9UQWdfrV9oWjMYsGjqD8ToxRK-Jx0IxQ',
    appId: '1:9527223797:macos:7ff0fec7a325c921996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
    iosBundleId: 'com.example.brotherAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9UQWdfrV9oWjMYsGjqD8ToxRK-Jx0IxQ',
    appId: '1:9527223797:windows:7ff0fec7a325c921996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyD9UQWdfrV9oWjMYsGjqD8ToxRK-Jx0IxQ',
    appId: '1:9527223797:linux:7ff0fec7a325c921996cbc',
    messagingSenderId: '9527223797',
    projectId: 'brothers-creative',
    storageBucket: 'brothers-creative.appspot.com',
  );
}
